#server:
#  port: 8083
#spring:
#  profiles:
#    active: local
#---
#spring:
#  config:
#    activate:
#      on-profile:
#        - local
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
#      group-id: order-listener-group
#      auto-offset-reset: latest
#    properties:
#      schema.registry.url: http://localhost:8081
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: h2
#    password: password
#  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#  output:
#    ansi:
#      enabled: ALWAYS


server:
  port: 8083
spring:
  profiles:
    active: local

topics:
  retry: 'order-retry'
  dlt: 'order-dlt'
---
spring:
  config:
    activate:
      on-profile:
        - local
  kafka:
    producer:
      bootstrap-servers: pkc-xrnwx.asia-south2.gcp.confluent.cloud:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      bootstrap-servers: pkc-xrnwx.asia-south2.gcp.confluent.cloud:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: order-listener-group
      auto-offset-reset: latest
    properties:
      schema.registry.url: https://psrc-3w372.australia-southeast1.gcp.confluent.cloud
      specific.avro.reader: true
      sasl.mechanism: PLAIN
      sasl:
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='QQMYNUXNZDGEXUOZ' password='9gi6uzOYLB3z9p8EAl/DXJBEB7CDgJdcQikIbdpkhQDEg3zLhLAdjQ5FyJkp9pRi';
      security:
        protocol: SASL_SSL
      basic:
        auth:
          credentials:
            source: USER_INFO
          user:
            info: KZZLH6AFGRN7FQ3C:ytMGKqbtn+S89a/VOpnbMfZkhWStJ0WVgYkZFsM9ABLQu3HyngKKzvw2XnDXh/xq
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: h2
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: ALWAYS